# -*- coding: utf-8 -*-
"""Feature Engineering

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IZY1N5nHsN0m6OF_FXdLkRVNDrvYhRAa
"""

# 1. Creating new Feature

bank['previously_contact'] = np.where(bank['pdays'] != 999, 1, 0)
print("Kolom prevously_contact telah dibuat ")

# Create negativee Balance
bank['negative_balanced'] = np.where(bank['balance'] < 0, 1, 0)
print("Negfgative Kolom Berhasil Dibuat")

# Create Category Group in pdays
def categorize_pdays(pdays):
  if pdays == 999:
    return 'Not Contacted'
  elif pdays < 30:
    return 'Fresh Contacted'
  elif pdays < 90:
    return 'Regular Contacted'
  else:
    return 'Old Contacted'

bank['pdays_group'] = bank['pdays'].apply(categorize_pdays)
print("Kolom pdays telah dibuat")

# Feature Extraction

month_mapping = {
    'jan': 1, 'feb': 2, 'mar': 3, 'apr': 4,
    'may': 5, 'jun': 6, 'jul': 7, 'aug': 8,
    'sep': 9, 'oct': 10, 'nov':11, 'dec': 12}

bank['month_num'] = bank['month'].map(month_mapping)
print("Fitur Month Number berhasil Di ekstrak")

# 5.3 Feature Slection

# Drop TO column predictive feature

columns_to_drop = ['day', 'poutcome', 'month']
existing_columns_to_drop = [col for col in columns_to_drop if col in bank.columns]

if existing_columns_to_drop:
    bank = bank.drop(existing_columns_to_drop, axis=1)
    print(f"Kolom {existing_columns_to_drop} telah terhapus")
else:
    print("Tidak ada kolom yang perlu dihapus dari daftar yang ditentukan karena semuanya sudah tidak ada.")

# Display the head of the engineering data
print("\nData setelah Feature Engineering")
print(bank.head().to_markdown(index=False, numalign='left', stralign = "left"))

# Dimensionality Reduction

X = bank.drop('y', axis=1)
y = bank['y']

X_encoded = pd.get_dummies(bank, drop_first=True)