# -*- coding: utf-8 -*-
"""Perbandingan Ke 3 Model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IZY1N5nHsN0m6OF_FXdLkRVNDrvYhRAa
"""

# Visualisasi Perbandingan

hasil = pd.DataFrame({
    'Model' : ['Logistic Regression', 'Random Forest', 'Deep Learning'],
    'Accuracy' : [acc_lr, acc_rf, acc_dl],
    'F1 Score' : [f1_lr, f1_rf, f1_dl],
})

hasil.set_index('Model').plot(kind='bar', figsize=(7,6))
plt.title('Perbandingan Kinerja Dari ke 3 Model')
plt.ylabel('Nilai')
plt.xticks(rotation=0)
plt.grid(True)
plt.show()